# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:xf50NN9R5Ox61C18HGfV7G0vHXX1N/lkrLyg1JVxF0IoCcmOb7HTIQc=,iv:A+WxbliHDcoRp9PHT/B34qMl559z3Jfd4/F/CQHgf3Y=,tag:Dl6n8jEJoVi6TrynKM3imA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:Izq7PFqmQ7Q99SUxUAqUwwnNHGRNkoDPphFwih/r,iv:SzyFlxirgT4JwK+SYbtYhk5eIQtI7riBEwQWW68DMOc=,tag:2YvgJiiFEonh86yIxm9rqA==,type:str]
    BW_HOST: ENC[AES256_GCM,data:tSZN7VV+GV6bypr0Eg==,iv:aHhm9B9CXP2WYL6Bo+CBkWqM5v8ybQUtlrehmxVP4BY=,tag:FGIoytQiWzt1W7JtYQg3yw==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:QCfWFzFqW1b2NF3E,iv:SsIrCNUAVxi10F83cK1aAR+SnSU9nY4/PSP66GfYVKU=,tag:TsgaEAI/HSrkWFNntyqHyA==,type:str]
    #ENC[AES256_GCM,data:djqZGVD7OFMpKC9s,iv:lwSrUfHSl6XPnXTjrsH0qILxTQNKfhToR87JcBduan4=,tag:8A2yh6TSZqUQtzozb7Iu1Q==,type:comment]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aDBoQUF6Z3A0b053MWlr
            dStKZnhRWnNxUFpneW9FeStuQVFWMVBWcDJzCjdQei9nQS9yTGFxMDQ2U2ZMODMy
            VlExeHZKWDBKdE5GRVRpNU1NYXF4RWcKLS0tIDhOUXpLOUhoY1pvTWJ4SFdVbHla
            ME5hK25ZM1V0UWhJREVhZ3RQNjRlMmMKd3G3kD2oyT/bPg2PKaMa70uCIlkd++Sj
            rgYe3Fg2TCAqVFslSez0OQ/sEablwkfHKqjfytNqBPShj+gGGJCaCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:19:54Z"
    mac: ENC[AES256_GCM,data:Pg39OIsYFslOND1pGCnMpLBvGDpEKaF2T+34GGZss/XPeIPOzqtVHJgeVtwGKIDAaOJqUOvxqwXzz5IbuKrL5S/gCvYUKwidXDfbTcdzaUyg3t6Oz7zhQJYEddCqZEaWFFvHdoNB3H+wMEJAGywd1cNW/bQek+JIUVF1+/Y4kEI=,iv:5Vha3RC+xuHtep8QibCmQ+1puUD2ubPCJpbT/E9zcgo=,tag:y9/PbuZlFplwszw8YVpprQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
