# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:vOEvSiS+3uHsiqAkkyubdMpXf9m/H1wFsp9nD36kgxZlYS3YyriS7CA=,iv:K5FE4c/ss63H8v2zDfwUE5cLw/4cw6De1Lls8Fn37Mw=,tag:brCNYd6IQ7Qui88ow32aYA==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:Tz1YhXhVMcB5EBH45n1HWO7nrhOruRV8ZRSgPWkn,iv:nYYBAKpB39ZgwBYfV7pq6UPwSJQI4Sc+v4UsHPS72U8=,tag:eboO09lK9e4WQ4r+SQlIvw==,type:str]
    BW_HOST: ENC[AES256_GCM,data:ElA2YshLNO+kHLk1DA==,iv:8Eb1XHQuPkNUPabiNonirK2Fccv33ms4rIc06eD0+C4=,tag:wnbY7JDqG3r5d7D/1Cufpg==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:tz8sbdAwv/8+aRb1,iv:wVo+3iPjM4gk0oQWmCQnhFZMEc0GwahZHoPk1kITe/8=,tag:bbeEr1YOHdWCot1MTB8TKQ==,type:str]
    #ENC[AES256_GCM,data:KiIIrnOpEBCTaFOf,iv:kvtXPHPqWRSHjoR8dIM9LgY6NNdrHAvXKc///h3CCYQ=,tag:d3xUbl2x68prcJ+2bazExQ==,type:comment]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0VS9nZ0E0TktsQS80dmRF
            R1lvaG1jS0FFSENBYWdBTUZMTGlNV3Q5NHg0CmRjKzdlTThDUk1tSDh6ZDFSSUs4
            citEL3VNYkJETjFnSlJsNHdVZHBWd00KLS0tIEdoNmtmamdaaVB0ZlZraUF1aHVj
            NW9wMTJwdHU1MUFOM0xLMGJSc1YyeG8KImCW7wmAOAvKbLWOlj4AELC0CJOIE6m6
            PYWA76mUOMHudCRR9suMm9enHpzRE2L/lWnpmOLKTzySL8EXDjUeqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:21:16Z"
    mac: ENC[AES256_GCM,data:fgR+g5GSap59XnsDOUzNLsIFmm//POrD5j4vnKQVBlJzp4DVkqZ9W1Eg78H6t7eqf/OERO2rfwbABPE9vvOOMEmJ9R209g1MYKdHkTZhgCvbon/6jHrAYCab2P5l1RGXm95rZa9oZa27moilXBC+2zqo2JwEolllO8dLAKmDsI0=,iv:ldlyKf4MeKuSyn/OrKwOhe8KGZV8hMqQnHPCrKsZqbk=,tag:+/uVdwSklm5Br1wENIoTTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
