# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-cli
stringData:
    BW_CLIENTID: ENC[AES256_GCM,data:icaTwxKBG/J2Vuf5Q5waRB7asjjMxPym+hitymQg6W8NyjZ/Ld3jABE=,iv:KwQdRp4mmk4I4FYefTB3bFprzsiDHdgAxuI+aMmEr9A=,tag:BaewJkb1akKeWJr5MbRWiQ==,type:str]
    BW_CLIENTSECRET: ENC[AES256_GCM,data:AetNrzQ7UwWcs0452Wz61/bzWKZTNS0fK83UVdtS,iv:Y3ShRH/3fThGheEL1N5poEMj7IVkxkc/UJEDYBeKuiU=,tag:Fkv8UXB0j5YxbGMvdF70wg==,type:str]
    BW_HOST: ENC[AES256_GCM,data:Z5ad8yxgEGWq7IXLfg==,iv:MlYXNVLep6ZlEx1mqZ5ER0v984L025mJX5LFFXJNujw=,tag:KbB3FKb3s5w6RY+vLyWQuQ==,type:str]
    BW_PASSWORD: ENC[AES256_GCM,data:XwySAjRlE7xVLmCK,iv:lTMw2zCLQuFxMSURPQnmEbvZBpW7GLmq3iCZKwATKHk=,tag:sBEUptc24v9y/DCI/3fOcA==,type:str]
    #ENC[AES256_GCM,data:8ldJL5nzW5xQaVQu,iv:SDhlCCQ+7jpDQjvtMW3HYiI0UxYBx6eeEvz55tqcDxY=,tag:LQr0WDH0SpHDVxCeUEyNQA==,type:comment]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2cEU3dWM2a0F4ZEF6dm9X
            d2oxeFd3MGViT3N0RjJ4SDhwUnpTY1VGN1hFCm9TQnR0QVNMZEFQVjhIUGxzV3dO
            bEsxZGNKV2hzdzFzeWxmZ0djTFBZbTAKLS0tIFRpYjFkOXdmQ1VQTzJKUFlWZnNL
            aDBXVnVFeUJ5R055UmxHYlR1QllvQ0kKkOnb4B+3575qO1vCoVSOIq3xr3xm7IoF
            JiFkfjBPu33VHMdnxGjhfShFbOn+W4XuoQCJpD4yuIZjPGlZ+HJaKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:11:34Z"
    mac: ENC[AES256_GCM,data:75gH/pM0izTlp1q8guHSRWQ7qgaHo59T4Ol6BPs5MH1imSMqg4c7ngSzuJjIj3czMSn7UHFsIvsSWpJjabeui91Oq7WTC8SAD2uqefFhGDRd19ahgEhtzoH5qpTR1hrrtTnLuBeWf6HTNFFNESaj0FGNGxe//Voih//AYLA4izw=,iv:R7K7KbwrH/zv3++N/wo+F91ZkJHl21sdaUVzqLS/vnc=,tag:Srg1xuCzQ+FdXw7Tuz0i9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
