# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: qbit-info
stringData:
    qbitusername: ENC[AES256_GCM,data:BfLNcIU=,iv:nnOFWgIGNuOZQPDNe2jXp11/waC8otRvchdP91/cf48=,tag:5pathk65YX4vlhKH3xk12g==,type:str]
    qbitpassword: ENC[AES256_GCM,data:/kbK7x37ooH8,iv:dFchjRWSdSh3/YaTpa0gIcjmcK3UkLkv5403tFClj0Y=,tag:KRdi0S6EX+WTD3tnZdJFvw==,type:str]
    nordwg: ENC[AES256_GCM,data:QdYvQI9+Ycudld0CqEJaicz5dsho3C35/q5ucvFAoygSrgpCtKrQNem3Vw8=,iv:fy8mFKC0VE9wFPsIH3vy7deSKqcHRDle1ycmDUOCSVY=,tag:pj8UEScYbFf2uwhjN20R8A==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQjlDMHpqaW1rLzlyM0hL
            YVN6UWEvVDdiYi9ZMHpwWS90OWJKb2E2VjA4Ck8yU2Vpc0svNG1BblBiSXgwc04w
            Uk9HYkszZzhmQXlhT1lHRWZXWU1HZk0KLS0tIDBTL3VMZHF4RHoxVElXVm8xS25s
            dldieGgyMndIcGxaamErVXFaT1I1RWMKfTJyKBzK+xMWCWvpyaF9b2s0tL/bd54/
            7p6BoOaQg/SktWBwwm9cafMhz+qkZs6oxf6L7tl0fFVjFUu2I7FDUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:19:55Z"
    mac: ENC[AES256_GCM,data:XLxl5o+iDvT16uS1MCXkoOnSgdKQ/0YG4nz/2oTHsht4eA2jniMsf7eZ/TDpTtvnfjVn8CRqafNJUTTL8DtvGgewrbh6K8muEJg+ILMrSaxoiu5jDwFk6kDNNtSQPZQodngry3SAzws5kTw8DWG8OIbxd4QIWAVxdxwk+aouubI=,iv:UWXbr3y2oWrpGKV9zy8IV6b+R0dNTdGipEsjv9oFZwM=,tag:319rPTCrP37NaUX4B1LK/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
