# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: qbit-info
stringData:
    qbitusername: ENC[AES256_GCM,data:CdAZPiA=,iv:NZ6p/BLXLf92ETOYr0KAo5RWkhqGxGIsDRqa967jnEk=,tag:6Fr7l4SZgdEZwHyGfh85Fw==,type:str]
    qbitpassword: ENC[AES256_GCM,data:XaiqDg1rO5pT,iv:mDQ2dASCbZHId3T6msWhuIFB2d9P5EHJdNHpqa8FwVk=,tag:PeZRHWE9SNciTGINb8DxDw==,type:str]
    nordwg: ENC[AES256_GCM,data:pK/ylo/MBtVUc5CHVknWyoN+BofxPXAqQsPKyTk3hAfc0pnMkf1f9bfOnTk=,iv:AWnCBoLCNIAo8PSZPxU8uuInwdsdv0JcXIQ3XuJ/Upc=,tag:U5FsPX9PaS108tyfid81Lw==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMnhvQUpUYUdqUjdDRXNv
            WXJWUytqSzh1aU1vaW9FL3pwM2g1Q2xtTGhnCmtsZDd6TTFocEEzZjdpcjA0NHhN
            NVF1c2pYSDg4Z2lhTEhBMkp2OHRBb1UKLS0tIGZWS2hmKzZ1Z0xvNTA5THE1b1o0
            VWlWZjNxc0xTQldtRk9NTzJtRDh5ZFkKy5HQ34rJzfhCwbG/w50+KmIhnFzFALjP
            5HTX9PKqfl90ul7K8RhwT2LqyY6WsrD4zWci3l7qPFgUP3gU/PfXVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:21:16Z"
    mac: ENC[AES256_GCM,data:jsjQlSnI/GFcHucB3ou1nV7ivoMe9XVyqGPPSOQ4kZ2WOPpKCgqZBG/oDXQ3Nx4PPmdRX6ftkxy5r8DZCVgPNNMWWoDQQ8fBqvDacWIbjrB4Pa+S86pXDDeH0WG55xNM2q0Bxu3TsG0MOgBtkDJhzlCZE2E5Iez9FPbi/WogRpc=,iv:OOPRIbxkUzy7Mv0B5nTaz+FXp6E2Jq0oPPkaRpufxWQ=,tag:XE3PcCNw6oOTt0qXquP/rQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
