# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: qbit-info
stringData:
    qbitusername: ENC[AES256_GCM,data:xd6Io9U=,iv:A621aqY9JFRy+BSrvySkHg6T9vwZgKnXhW356pAa6mo=,tag:eB1wCIkGrb93DdzB3E6Itw==,type:str]
    qbitpassword: ENC[AES256_GCM,data:JEdfsmTVfbz8,iv:1okfvRMmqypsCDsdT7g4erl8BXq116k+QmPvYLGYeKk=,tag:InDZeDmgfshfGeYBA3J+VA==,type:str]
    nordwg: ENC[AES256_GCM,data:NfRyh6g1QlkBDw+y8kIoJZeqqpem5RhltHyi6O0Wv4rzQBq99BLbzBRJD8I=,iv:GsC0H0+BJ6BpZwntvYYTlhvcL1+E5/Kuy66/6jxLJvo=,tag:FytzQk5EwMPm900QBzYdHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0WFpsajRXYkpRbEhhT0dp
            dnUyUHluRU5pSUFjQWRzeUFzWFJZd1U3bURVCk1DNlhtTTJ4dUROWXZ6RlZjdmI4
            dzgrLzBhcmRybkhpVHZDN0kvTUxRbmcKLS0tIGVESTlqeXBpMjVMM1pWRDd4Z29a
            YkZzdTk2WVh1eVVvMHZWUnZyTjNMOFEKlWr6EyIa4yd7rjamS0svrAl1zPCx3IGs
            DT+2DeWAQtRbbByTBCRfXuvKoIdmJ010/S4wtXdTdfJfWAXfsLB2GA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T02:59:06Z"
    mac: ENC[AES256_GCM,data:cZrNG92E8P6YhNfReiiZhZ5YmMdApfsm0/Wbx230i+HsxwQLNZeiaHyrR7HXi3HYM1Ep2mMYhRfkS8t4ayh6uEYE0nR1hB7O7dfDf3pL3pjMS4KMTQd2HWmNsMCUHRcp+ciTCdXIs+8pkirz8PFuVwW/Wmj059LN9GciIBfJOzQ=,iv:tPZb/q2qXe8Mt/CtcIMe0CPj46w9+PjJIEoj1fWU6Jk=,tag:Acco1K/gn3jVIyBbWizd+Q==,type:str]
    version: 3.13.2
