apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-password-secret
stringData:
    password: ENC[AES256_GCM,data:jH9j4GSrD2oI,iv:r2MyhFJ4avfVfQ4kSCnZcKYBFplgOCEhkxxsF/TP3Yg=,tag:IIbe19ruhENSzeV70UplNw==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndUl4M1BJOCtPaC9maVRJ
            aUNxUUJKS2wxSXJwWDRKZURLVXk5Zm5KbHhRCnZDeGJWYlJaWlZ0SEJsNnU0cDly
            djhXNG1QNjlFdWQxYTV1Nnc0MHQ2ODgKLS0tIGNaOWRRUU5RREY3bHpqdjZNOHZW
            WmhYcVFxQUdRaGZuQjVTRURmU3pISk0KRdBfs5kezHsMaVh/rRHQkFhcFQdNOg94
            riNohVWSYcbRIqAWchCPRKLo6UZI5hrvt8PJbCcP3BItRxweNd6FaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:14:14Z"
    mac: ENC[AES256_GCM,data:GpmyyDrkHSTt8tNZHGK9GW/cvvVepeU75VqL1//eHl2fj9kCrk6ko4cNXaMlWnp/L6TUxOcmQwnf+UcL860WizfIm+1CcQFhGrYCD+zvlu7Vpp1PlvuiHTBIHCDXD62lx/P3zq3LjqLJ3wGJZU2nFajHOhfSYtflXPhMKMr72BY=,iv:drf/AWom6wx9/8qWyS/HsOkjRkw30TBw9apYT7Uwd/4=,tag:rAS4idIWHu2JBm5PkiDXog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
