apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-password-secret
stringData:
    password: ENC[AES256_GCM,data:xxENveuM5qMx,iv:rjSdf343dVwVcafbqJ0EGcoXFdyYZ/T10WBhogzGEf0=,tag:b6PTRa5IZ6Hfl0LYOltH5A==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUWdXbjhWckNwZTdJcnlu
            UGJVL2JCRXJibjF6SGtUMGtMRUVCeDMyT25FClRUekgrTU9WVkpZVDRqejJyTWYr
            T1k2NnRxOE5XM1hsa3pHQ1JnWVQ0R0UKLS0tIHgva242SGNES0ZweXRSWW1tUFNZ
            cGpqbTkzdmRTalV0aE1jOVZtdW1FRHMK83pY37xDnCFaDk0pZnpmi7dla5I7Cn/4
            Nx/WMD+8ZfbcnUat3xjDS5wxASJIZRaJ8iye6SE6pNel5vUUOvMPYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:19:55Z"
    mac: ENC[AES256_GCM,data:ROxtpU8QX+isEpfi2mnHK6hKxkXeKm6gvRVJcOCxmeE5bY4UcDUb29xTNkAINW6A/UpV59YJy+wqMdYzFvHaX53qg7qAIU4kHkCMfV5eC03a6F65roW8gwkqrkpYIv4Wyd75mtGr9TitOvQQlukPh5LZaolBADDH5cFAW23wQ3o=,iv:XOuPCk+dJuJFXQWgveDW44qNBpqpN/fi+WuhsKAxXTE=,tag:AHlGR9JliZWAuihoI4CdFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
