apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-password-secret
stringData:
    password: ENC[AES256_GCM,data:6BxsIMXK9ApZ,iv:Hecm5+NTCxNmT2HFQXbeC1cFh2VWALTcdQq9M4vhQM8=,tag:oNFBmTH4bRrgXASXG2BAiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3OERYMXQvTGd5RWo0bWk0
            cnFHTWJ4VVl3aVc1ODc3UVJHcWFYdU12cGhJCnI2MmNFNElNSXZsUjFRZWV5MVBW
            SGViRWZJWkNBckJiZ2tVQWkwdFJxeWcKLS0tIEsvU0hVcUlnemdLM3QzcGlFdzVj
            Rnk1amJmQjV1UUVSemZSTmM4aEpnQ1UKSExJ88B2/RLw1vj1YMd/M3oTDNUb6tQ8
            xaKwQ0gAj3S/llu6LIiuPTP3dkbMc78DH6CSl7cbDXTLiP+75i4ATA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T02:59:07Z"
    mac: ENC[AES256_GCM,data:nzehy6s8k3g25eoqAbsSbyrtEIlNxFodlBzhjR7xcFCC9PKsrI+4bAgW26uYBZeKhFT4ld5SxH25ZUnJnlunFa4kJ+7ooDJs5fEeE3o8qFzwV0ypucAfefbugqmri1iUUd213YB5/gMDa+IPMprGQm6AA14AMb/1vZeJHezqxsA=,iv:RN/PLdiqMllzA6HK2XbeeHqcl0rOdtIfTBCE/4B1NnE=,tag:l4nJDcqPNJxlUnRjOjVCDA==,type:str]
    version: 3.13.2
