apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ASjUoFvPPqLadaoCSFFOJDFoKo1leoe/6ZA2xJIHveYEQKag,iv:/AkII9BoOaWx3+17U7YWxk+CZHfNR7qNXVs/aVDlSd0=,tag:oBKYdYLDFiswObgGvHux1A==,type:str]
    credentials.json: ENC[AES256_GCM,data:zzzLvExUBu/IFyENBOaHrRtkajrXk4P2MVNWeKo/wkqnVsRYe/DqomfvTmFHIvhzdnshfg736RwiLGPFkGa32n6ss2UQg3tBhGg6JIPXkkS2Uw0c7/qMNCVrDUlcffetIlMDJQb5dzLvqCXQz6K7gi/4RgB8mvmIikmxLPneYP/IIpvtZ39l/Ufi+27KJWvrkTtdPTVD2/gp4iGD7sx1aOlNt+bO8eGxrlTzCv+fDQ==,iv:5eV9zT8Xq2EYz5gTDyB2dq+jT4MoTFTOZGu8INNMifc=,tag:tyUwQZzkkUErui+2KlCAaQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZitvRS8zREc0V0ZGcm9q
            RDFpM3V3OVVVRXM1c1NZVzVQeVA4RDA5czNjCmd5VHREek9zb1RISnBmblJCdmoy
            THd6M2pFQXdQMzhoNXozV28vamRJQ1UKLS0tIEdSODRZS1BrZmcwM1Uza3FGckZS
            dXgvYTNOUTY5ci95RmdTRDB0Z3hRVEUKeNaxpLXTAXRF268qYGgVNp+8MLEBghJa
            1BTMbJwHGed1p+Xp6uiERJWjXOKaHXMWgVWFddA0qCPEWq8RHfdHmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T02:59:06Z"
    mac: ENC[AES256_GCM,data:YyQiGPVs1gjBaEChq6SFJrS7ziTX0oe0+b98w9K325tE5Lj+AN6BRKjYDzDaWcUIXwOCXHXc8QJ9DFTx95y5wUmAGJohZkPfxO9nQZBR0a95YxivJAA28zafHxVz+Nkd85/4liTNBc6z8JW5MSO/tNzrON89InIHxTLywkytCZQ=,iv:kszJwtMb6tEzvGxP560S4gtFlqWFkXu40gT0lwc1zns=,tag:vKoqp5SeZHOH8MzQG+7iqg==,type:str]
    version: 3.13.2
