apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:4hcp781XeKgtczMJF7G+QZMvkgQsfh94sWv9YexZD0fOph48,iv:j1l8qdIANTH+8Yh2PWazR0NkIBhUK4tMdwRz1gCZVqM=,tag:P16Hf2rUQAs3r6ux8dAB5Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:R5T9i9gPm9ecG5Ois9OPgHkEkSkeN5h8HMqwOj/LKg8Up9NBnFxxsr3m22cgR2Rxgj5Kt+07f2MM3YlOpDPJZ7rO5POzki6fL/u9BylS4PSK5dz61IOuqtUtvbQqt6V0xdLwC2VumFJV9CmRSz1RrvpG+90dA6Ol0leoumJu+I++9wEHAWXMP/sEC6ieqSyuY2jLzqWl0Axev+OdyU8afu/Lo4YqyZCTT4OB/W9LXw==,iv:eVLQdqbeN3kht7v7rL9hsGJLSdeK7KSWaueOVYEMhJA=,tag:4TSBPt3mmAwlJ5Nq9ColMg==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUmRuWnVrLzFBdzd5ZGM0
            WE9MelVlQmJ5NGxuMU45VlVkT3lQT1JMVkVJCklxcFh6M3lJWldrN0pQNGRXYzhp
            MnVYS1l1anBaVHBmNWdDUWJjempta0EKLS0tIEFvUnd2bDFEWG5xcWd3VEVFR1lj
            bnlSbjZiR09rV05XSGFwTnc2MHVKMmsKQMEgEoE8l68O4vC4OwwtVrt1RXdQ8PbP
            2f9yrQuTFAaHS0RcjDmhb/Qknul9p4oCW38det1bumRJLFOMQAxFlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:21:16Z"
    mac: ENC[AES256_GCM,data:KtT6/QIal1eIrvpV+42ZDG6x8gMgkzTIsHtJvHdTbYFPXanh+cDSKbWGUnsRYiah1Qm+J+lygsMy7lTJgPkuUd/d62Gmwkv22+XSfkmf+AiPYHWQiqkWFLdXyQ0ItRlymikr2cIs9xYScYRCQQLRs7ZcPe0YDkEAolDHSD4emWk=,iv:TrlbWqvrPsGYODRRzMvEqxwdeqx9eXhwd4v9vOOn4/M=,tag:wULyrBViv/N3P3VsSq9FEA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
