apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:DapIYXpAVyGW4jJWcMhAblIVEBRPhGrw3eOct1cC7a3qcNXs,iv:jxaMUqeNeK+5pPWzkmBvTaMqJfArMDDpRgWE+40+EMU=,tag:sB960EhtuAqXW5AvGwrvHA==,type:str]
    credentials.json: ENC[AES256_GCM,data:CsSqIH5euECILv749lXUTPgZ5HGwH5/gqT0vow0xZ/95kkp31lSWxoWRofvypB4AoPgoj3r5pttq3WD93RHz1mJ68JtOLKf1ejS8NBQw1k0QTjNc6689M+Din+4IJKqwQwan0heeoOBuKrSsnISrcfCxSzCO+8b2sdWoFcLcSsBGsABTH1eUK16mgIp693kGMAPxvZeZ2bL74+3VKTnLnm6rFXB/MeYw1138m1Bx9Q==,iv:vfVM7dIpxuzYyMsLO7kvQ6cHXAGcHBXCnf+lsIDK5Y8=,tag:MQnQkzQ1FLIPvJHueZYccQ==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RDQxYnZCb2hKK1dBMis2
            YVVBYmsyMVhReGQ3N2tSRk1sN2NYTkRlMlM4Ci9Oeksxei9sU2Fub0tvWVB6TE1p
            WmxlakZ5VkdNZDE1ZVZja0tZdGtaV1kKLS0tIFF5WXlLWTdxb1FXVW5VcHZaTVBa
            Y05sMnlKQkxvMkNGVUhlMWNXM3BsRk0KUkGbgGExAd6uzbv4rpRIoxt3JDs+NN8u
            1MZAKWanNLY1wF5lsksAIJtysXgDovIPVhYxwcePXKhCLSBVddDX4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:14:14Z"
    mac: ENC[AES256_GCM,data:6SBqUQXXJCdhcL2xqY5BN9cfraQP6W8LuQ5vUjClGYe2bgX6VyOxqtZvr0D/QXbT81egYY8bInnukGYYSJSKxx8ZzMp7/GG/G+zqZ6V9Ig4LU1yS1s9rcM4vXFbtGOM3e8xRxC/lUHmXGlVKS8D8EN6vYfFZzVUI+OtQLaRSDh0=,iv:xpPCOnVzKp6OLhr+sVx+S476F8pVJSY7vgBx5bSotyE=,tag:6g7Noex0yk1hP2hYD3t6rg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
