apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:9F/5sspKIp5I8cAvSUd3xhUsp+wOH6FfrAGzY8DcPJfCaLJdF5jATg==,iv:9xU0wiRKm59Gmh544xW1iWTXgHUoZEBXrAPiLEpCo6k=,tag:MTEzephHT9330m20zfF1JQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNUJLOUJuQkFOR1J2c0o1
            b1NleWZ2TWpVYVZXWVpvSXNhcEZic3hYQ0RNCkQzQXd0bjlOYjdSNkhWVzdSWnZi
            cmhzcEt2VUMyOHFVc0VNSzNPYy9PTlUKLS0tIElEYlNZaWUydWxkQ29LNmN1NDVJ
            N0g3YmhQdDNSVXNzSHRmUFlaVFZ0aFUKvre9rwVyZ3XYyAPN9GO851C8Z5dAq3rL
            OURaTaWSr83Bj2DleRu9yd7jhSNEL+E6hwGZ+zc+r/kPX7wVQ8QsDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-14T02:59:07Z"
    mac: ENC[AES256_GCM,data:uIaxUo+WSCx/YQQOFlAVp0woZ4/11qSZKNO0skCKiHzgIiNu7kK6lesw15JdOaviziFnxBaDcIbqy9ULRwT1GdRWbeFvA0vD9voelM0l0T4MJ9+kWccNtG9VvseNVhkgoOvIpD+L7/mbxR5vRczZOBAuuFT+bQ/cZnx0bhIWMCQ=,iv:hMI+bY/v3ba2xmFcULUS8gzMYmn4LNFcCcyQMwuwnqk=,tag:bAW8YL6/krJIzffpQA6HuQ==,type:str]
    version: 3.13.2
