apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:y+e9LGid4gBlUzTJof/J+LI4Htm8Y3Zk4i4BwMPSK3BuMSKGgSYPGQ==,iv:D8b1w9tZDMMK3f0t2HlgleKUI+708TYDJj829dG15Js=,tag:VURxHVa/r8TEwgjaSi2PDg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmOEE1a2hCdFI2OVAyS2Y5
            d20rUXg1VUVqVDZrbTEvRnFkRzArL0ZOK1RJClp4bTgwRFRuUTk2OUJiSFh3a3Jq
            R0E3TVhmRVVkTHJrdW9IbHFlSXdFSG8KLS0tIG9TdDVDbTBTQmNhdjg1NjdiTFFY
            N3RhU1pHWnIyWkFXMElXSzhLaklibzQK/YWziIADB47yGjdYeeybjp1C4284BRUL
            G58f+JjyNIiYKd5HcRMu5UiQzLxEo8hSBwITHSahXuvscneLjmPKHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:37:45Z"
    mac: ENC[AES256_GCM,data:br73XEjyoA959E5/raMJD44qR9j01qG/C+O+PsUQ2lE9E8NmR0dBtUJO4QYgrQqHZS919V3eOZlsY7aQDoWQ5kIiGJx9Xjq9jbzt0JbiOkrO1eR8q2ZG6byYIfHc19GnVRWxBfdN7h1G53/GdY+tg+aYZ8S0cgaQqijs8k9KaKI=,iv:jPLN/W8JjbUi/hWzhSmtp++8+rfRj3fsa472ffPYIKI=,tag:bmqPf4LvkoEWS3yCjP0ioA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
