apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Xu9neeMEY/jb2r6vUosAjJlJxE8fS9LArcvQ7mkj1dYR60exlOyKLA==,iv:kUVEQcnne5oTZkx6aJMQeSDrT3bfL9up65zU4mVNR0g=,tag:JFGFpEyAKlxvBPJnlKYbrA==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCM2lpeHhnbnk3dkVUWmNQ
            dUJNRTFUNTdLM2hIN1BFMDBvZTRDbFFwTEdRCmQ2ZUtwMlduV2dDTzcxSXBhRTJT
            bEhOQ0F3cFZTVnVNemV0eDY3UE1pQ0UKLS0tIGY2bWZtU09sZUwyM0VGUGkyKzh6
            VDZEWDg1ZWtOSnB6SGhnMHNMYVVpUEEKrzNnVHm0kn2x5MLQEGUomduajvm/xoJ4
            ca+X/Hm9kGjpzO8z5BlJJmy0NFW52hX8dTLSuWRNkb8Kjk+UpKmpGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:21:17Z"
    mac: ENC[AES256_GCM,data:2JLMq3/zamqFYbA0jYhw1t5JKp+Hw0NLC2Piv2kEqV0SsMoFZTXBPgmeKF4kaoSsWP2ewX85uIj1EKwlkOCeLyg2uGY/dfWJO9mS7NUz9Ib8sQRiToeN5TSdj9lc4Z+pRTTALPCBlWA9/4Z0vRpjd8cNhxmq4W7XJOM+zG8qqdQ=,iv:lxhV7ze5taHiiq5E+enGHmYs1eFe+vzCBRXVI+bo6s4=,tag:Nto6UtyhG66iJZOHCm005g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
