# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: hoarder-env
stringData:
    MEILI_ADDR: ENC[AES256_GCM,data:nlnhP8/ydsnoyCQiw7bxrOEY7dtMdmk=,iv:5iIMAM0F+vZFUyII+IZyphMu4FDCrTLwoiJTrDDDN+I=,tag:SvPJk6cbT/SO3H/f7kkNsw==,type:str]
    BROWSER_WEB_URL: ENC[AES256_GCM,data:uXXDUyArtvdjow9pN+5yXwCY,iv:i5/2zv6bgluwGOLMye8coNPiVUoCTE3JpdHYC2FJl58=,tag:07cv2/7EHIV4RNhTt5k6xw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:kCA5tdnHGVhDOiBkggvRi8WdfdCXuVxy1tgmg7KgmEuxjyi/jNQsMRhoGjomiXCUfiiq7QQGNqvnaL637mGNFLKOVhgGK3ru2hi0scLuCLpjlCEC/ysYTsBqrG/u9dSJXYFVRmxdZflSrO1ZSX/rqoCW/JvOPORHD7VjlTdUTTqOP3uufkBNmL7LlcLaeQZHzHe57u1pyqn/EH56RA5/LKDuaJU=,iv:kzdhwSQFvZtUW4QhW592jcv+hFPf2MQlCHI6kt64s18=,tag:scHEDPbXMA+Gv0AhNiL9ZA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:aVrGGK4LXKkUvxeGh7U7xsFfyACg9DNgSE02KXpZob5dRzPS0FzAIHrbmFR8epSt,iv:wgj7K4NQSkOpkJP9NKYvgjeIMAMNU6joknvF0gK2B1Q=,tag:AXejVnFqux4xmySMuy50RQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:FgzoFWn29NAp/VC9p7dAr2ZGMg83lkxrgfb+cmTfWVLQBI02YMTzJHGpx7SoYbsR,iv:RAqk9IvualP1Uo+Ret4dze5RpkHG0nKY12uqqz8/FMI=,tag:T5JGbhPat0kT4emmqm0W2Q==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:KQudKLuMiJPtHnTOxRgDZHArBQCmAmS6E8Y7uVo0K4USPj91ZRJYU/rblm9mON+D,iv:q9XC2gbhQpmRAmaVnhXCmGIBMRDOUYJhTi/N3ni1RRM=,tag:6KBSEfRdUbEiwei6O09A2w==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:MCnguqiDYtbeKcmvA9IBmDyWwPwCSoaP9bpmOkKD3+n/pPzAvZgublP49IAxlZSen52ZV/xOapKJ/wzwkB93ekinRRhwLHVfW95g3jDzrN0LLl2zHdQFIDl7ZthGXUbxWur2+p0123jRL/oDhlgQjCB5xVukpOlu8PB58g6QT08=,iv:oXrtxAkbLc2Xq9aQlEL/jJEn2xE1xmpwbzYzhjHJL1g=,tag:5e7zQu8eIJMSp4++9GM5qQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:sLs+8c686+0FUMS6YVVt9il1ePhvYrJOcIpNpa3xdD1PHCRu1Zp4gg==,iv:QBSZt47aqONAPIKzcawEqf6mv1JW8eD8TsTGUDF/rgA=,tag:1iRRcXkiL599D5t9fp6jgg==,type:str]
    OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:zk+Ga6PcSZBEM+4v/zwVGgmU4CEHaWbu6mY5BPdqXg/EAuT9Eug/iZtdtHONbZCMhd521vqFqs/5nGOH+Wy2atKpdFXRhk+cktSIVIOi,iv:0vUtB6Z18+Hjg3oo3sP+SGtw8+RCZZkmih8h6uIo6TI=,tag:A3fGAqh1bG7CfuAL6XPKfg==,type:str]
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:Zrav4Q==,iv:UiOMjaKlnmhg4ZfxwIEVt7IkxZxHJXipBK/vLDI6EaU=,tag:6+6+nuFo4sfo1jI61/rS/A==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:xtTp5+di/alDlEZTSik/xjtAeqY=,iv:zuBPTcjzmar9AGtr5MCkiSgq157oMOC9IXXY0Z4G7IY=,tag:Li3sG1cufqNlmp2wbQCppA==,type:str]
    OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: ENC[AES256_GCM,data:MX2GjQ==,iv:yHzEeFMwqgS/S1W/jv3k5y6mP1GdmBnRiSs69reMPoQ=,tag:vrWqlDkW4N8iou09RXXgaQ==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdzhEdTc4MUJJeHZIOVln
            cWpNMWV1SjM2ejY3M0pIdGNSakN1YjJMUEFBCnZyWDBmdWx3UmczeWh3c3dUVGc3
            bnFTVVBZQURaRnFMNmI3dm1DTGRpYU0KLS0tIEEwNTBvOEYvajRuMEhSbVl4Q1dq
            T0pCRithS2tPZFhsSmMyckFrTVpCMVEKe30Nz7EoXr24NmP4WbutvYK1QzOmzk9X
            3r3LuLorB6G4FgDH9aY6oGUvL5/F51/rStGnj2dtssR2iOdJnoSu0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:11:35Z"
    mac: ENC[AES256_GCM,data:HrZXDSKzh/qBAvpyOmipPfa4ATZN5tAnisp1OF85QOh8PSHHHUBCbyjvsEKCsU2IAfVelgF6G/keMYRg75IyV889uYniQ8ZcYZ1gUzGsOfkrgpc6ZS6l8pYjiGUqci8j6DJm1IUCwL5G2zq75muX4pFKW7dHgqYxbm8f8pAeQqY=,iv:ZGSTkekaVrbjhidqgl+H9X8TzlwQVLalRZuTj9B6r2I=,tag:+C0kosnP5bR2pzqhiPnqHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
