# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: hoarder-env
stringData:
    MEILI_ADDR: ENC[AES256_GCM,data:74D29Tfov4vFtPOC2bJAa4I2OeH5org=,iv:VRmYBsBXzSiR70xNshmW4yYYwG5wDIV0pZMDVfApGWc=,tag:krhLKCENbXQyzng3wBV/GQ==,type:str]
    BROWSER_WEB_URL: ENC[AES256_GCM,data:Tm25isI0Okqrw+rcqkNFiFR9,iv:7Q0Ns8O8wVIga0rwB6PDNXLadOK58dnn+y1Ld8Xi5A0=,tag:qF9iNlmjQvW/yVzaWRW2hw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:259Bxj4B0sKaBIUPKf2Q3BbpdXhev47gUUFMdPt3SMCoF9r3LV+TEi99rsuNGu/e4FULNgtMCs+0yK/b0FIxiDcA6/zX+xYE3bZIpUEam3tpVisJaaqTxFL2s0cHeGrZ8DwYdmK5rgJSDbng+6xyUWZDpCOSEmMii0RNwBEO+r2RHwC0D8OtgUjfZQckoBZw5lTGPGsasdrtNpvCDx4AGWlJoIw=,iv:XIeebBIMFGmTe4qv4A6Vg+jpy8W6yBp2K7VmMNQdcmc=,tag:Jb+UJ/OcqRSN1sbVmjMAIA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:51SpcUFalK163zki9qJuDUXNNkRfJ79VY9m+iKmKx2CV0mnT1j8U49c4rDlqlHcq,iv:Py1QifNXK+TeXLopY2+9408Jc3tIwlFH7d3noVoRfmk=,tag:tsxYNzRb8qc3MccUGV33ag==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:hBTCs597Ts/aunIiwiZ/SuOAvFOYJOsZAW8HcLnCCmsQF0gIIloXSxwfhwYWaw4l,iv:Y4MmW6aRUSp5gkptd1JJ7LU9TAOVbR1AQDH03HxacVo=,tag:gyVJmhdOlyYzGQmZw6nZCg==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:17S9cd72zj3p5jEOxbcex57+++Wu/M5sN3IwYsBwXQsdkJAzxRyd3vPd423pzgiR,iv:V9PUoDXfcvRIw8PQPbmbLAas9u0t+uSssc8XgRnXx/s=,tag:uBJAuSpS8cJAwYDy3XIEOQ==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:shbR/9QXmdc3pvHRI/0fNAxqj4l0s3awIC7TaklvEARTuwTGxyBbfeVshOAGizNDwdKsNy4DqwHT74daMOCYypyhfG2Cw7GP/mZC6FRwUkEp7FqYFRWS61nb48joJm/5IDXfmX4E1ad9Q7F7QBzKN6RDNPvPHmnkqC15SE7jFzU=,iv:nrO9g8+YZAejEdOyKO3m/GkjfcJ/xSGV4GQEo8A/wY8=,tag:0w5x7E5KQDpA9IH5GWyzRQ==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:G+sHBeOYNgKn4C4fFEn3hcKO7WF3MU7v4hemSZlYnYaQs7VFA9gH5w==,iv:LngxNHApZCLR+kcJqNa0zzAMZ0E+puHNbjEyncVvl+I=,tag:KDMrRy0gRGvy2c6lbuc0QA==,type:str]
    OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:GklPDUuQWKMaCjrHAEiEx5tUrTxjr12+izTCsmjEjfMXdtztUjoQetSML7TRxOiMiXPne5fBk7Vr5b7ofWE0oyurGlwZsb6En0cvksi+,iv:5COAekyqgXkRdcuTQwn0ozk8TA5phqzk+azGupMXwRY=,tag:WyRl/jx5roXGyeq2fd3INQ==,type:str]
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:Uu0T6Q==,iv:Oxo2jFBUl01+U+sNTbrd3YfA/06Fd7NO3NI0sGktP+A=,tag:lkrbaDBuJaNXhVJvUU8H0w==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:Z+hUHLX4MK5NEUH242wNXZyAQJQ=,iv:70NNqG+QJ71XYaqI4Ac6GrkStebL/nO680BnB9WPkXQ=,tag:RSBWzhnA+CUEfJ15aUIUIw==,type:str]
    OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: ENC[AES256_GCM,data:xP6TDg==,iv:Yi6r2+D0uITtlv+WyN63dkG8G3jnDX1XNn7DUMVrkP0=,tag:au3pbZ/vdTjCQa0vUg2psg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L3VQMGx1OTFFa2lDOXBx
            WGdBUitPRnZiR0s3amM0WFRtT2tXVjE0WmlRClBqUWQxYnhEc3VhSkNySVgwamZ3
            b2hUb2UrYW1MSmQzTnY2bDN3M3QxVE0KLS0tIGdqYjh6dWNIMHdzYVZYYWltZFJI
            NXpLSHFVbG1uSzhaYTF3bklCcS92TDQKspyChYFqwz8Ie1akSOZ5qeanO9eTFSEc
            DmyT5xbWrL6q7EUuuue5e9S0uXXOM+HlG4P/+UE/XNBPG+wpimwOcw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T21:55:23Z"
    mac: ENC[AES256_GCM,data:Aof4M3BPFFqqk+x4hN+zxLOSK5++dr1dqmREfQs04onkLXTY999oJKGS4HYcTT4JL6S4iN3DOsqm22dH90eQud2GrVlPcK9No1eUSv/g5pZ2JHSrKrRKqeZM0l1SFzZfrR+KFPVkE7EDPHWtf+VyF8ETh8Ip8Q9ZFWZbMIuiA2c=,iv:ijWeSNtyw4NUZ8dGfvgJT/jXb65G3m5mAEIENj1m9hg=,tag:DpLEjGPmhS0Lp3hN6HM3CA==,type:str]
    version: 3.13.1
