# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: hoarder-env
stringData:
    MEILI_ADDR: ENC[AES256_GCM,data:0TbydC87YFuaLhRRf1YXWIG0jnxv4Zg=,iv:x32M0SQ8Vqs/1F8A9HwDruSi7xfRLnVBGLUScmeFs8c=,tag:8AGVA1FizzWjO0xO/KT5Ig==,type:str]
    BROWSER_WEB_URL: ENC[AES256_GCM,data:jDIKlL5hsWa4oTiz5NmYaQi9,iv:DYTkPmPKMjN2B4mpwOc3NUitJOTM9HFhXBefcR8rpDA=,tag:t1WLTNeE47sDEqamsZ3YVQ==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:Z7kAkUdcz1MAi7eJoxbK2pXWwxBF9iJ4LNrb/7qz5WZnBJU7p5OYRlTLpix+XY5xij0/O2w5r/tHJ1XzakIcRvseUNU5fFCkxHEgHeSlUfNwmt2+1R63wc9IeCgZuwcS4DK65TcAdYMSnQsdalOYv+Wqp83KpUEPUATA6sifcbdX92bigWgKXBdkTj8nJc4858hNHIhnfUtxc/Y9m3Q7EdEyW7M=,iv:Oet8hUgbWSNwHHC8KXK+aMKzMyYK8Yd4J17pqpMISUw=,tag:k3NJlFFkYfv7JocM3tUh3w==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:/2rmnJ3nWF67LzRr883Yz1iMKry7XvjSN4Gw96MCUPBXNRoqCb5Z8okvdATBEO2Y,iv:hQoXqRhSrZR3/fz1LZqgYgcsqCT4/bXZzrqCjEuVwAk=,tag:vZ4OvzpwM9mhxg9nixIDhw==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:pJ3bzxYgBUGdSE1TU+Whhf4oWhEJSntQy3Wvu6ot6qUQyeGQ4/BdD86UjAOxtD0s,iv:1F515fGPQ5S5/0tOPv8qQMNF30Z2D9tAKDQWPEAEAZ4=,tag:Y328rQDfcMrWUsY9l/MdlQ==,type:str]
    NEXT_PUBLIC_SECRET: ENC[AES256_GCM,data:jWFSbz3++K0Wg5PE/+Kd2pFVlH82FyWvtflDvQyvifeuQWY1nc2VFSQwE/Ea96v5,iv:AVweO0YJMTMnTPcd3nlHQWGcwb4u4/iuzZ7xmK8l2cU=,tag:5KnT0gtvY3e1+rnIvQTg+A==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XJbtWb60ly8t/5oPfYibm1i7YjMXcOz9tj8KBoo9drWYXmfOi03rllW3lrGcNv/kPbFrePfPXSd8nGLcF6e3ZSXMQaBU8VcnkXDp4nOmcr3MCEB3zu1hmFONAd/C/HHyyhIRvFEFwdngyAbsz6n2hrEvvE71UGIshCIoxwHh2kc=,iv:bk+ygbY+vbJrYYQfSM84ZzsncHMQQgY2lTN8juB/9Z8=,tag:neh5u2csMtla7UL4HRa/Zg==,type:str]
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:ET1no0T0r4vZXwHJPBVae697VTZsliclmC5XFQ9Q3dqA71MflDaprg==,iv:isex+sMHMWmfuIEMmMJcL1/HpONAuwhTt2qNE8myMRw=,tag:HWFIQkqNpsBduwtYfIMGQA==,type:str]
    OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:tSPjQHyeFfksTAv7UbJX5cECpQUS8hhZKY84oxR4NMkCHoNTiVdxdJxFBvwTHIyZ55y8KUcx+ztpt9M0wOKxPBHfrhLXpAVt7tNbfnUH,iv:X35b15g9RZlk9QlKhb53PTib1V7juaMSpxbHqSTVogU=,tag:IbfcyQzS9y6ObckUzXd14A==,type:str]
    OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:O1L1Tw==,iv:iZN/t0tz740miewnvQ2VtpDo7rTinPloYN5UJ82kF08=,tag:LF3llD0R8k8GXs5lhVxkyQ==,type:str]
    OAUTH_SCOPE: ENC[AES256_GCM,data:gew2Fd+aikdSjD6ElU2BWPFzvtM=,iv:mz2Hk6qJnvAYst3OoOwwWv7amb03PPllYlHP8z8ye8Y=,tag:LgoAucx2AokEzs29H7DKVQ==,type:str]
    OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: ENC[AES256_GCM,data:1ik/GA==,iv:RGetX/R3SuZO0wCGJMaWL2nGo3AgZZVAHO4bVN0Vd7s=,tag:GSNsZVoax/dPDN/ILPmrdw==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NUdrMVRKdXBNNHFGSFFp
            WXVBeVB6NmFPVzVlNGQxcDcvMWI1aW9mQkQwCmRta0RXQWEvWHlKVHF6amhINzlw
            NWF3WWhUNmVuYm56L1VQNEZaUUpYOEUKLS0tIFlLNG1qb1NPNVo0c1BVakpHTE9P
            RUlTSWdoQmNFRStpTWE4WXV6TUhZNGMKC80892AtlHXMqCUU3XOuA/fFx9pcFrbZ
            7MAWy1lLxoefsrIsJlPvoPgVeG8NrkjTXQmGBvF/cywJrGT3aWO/kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:14:14Z"
    mac: ENC[AES256_GCM,data:cuaRQ2vSwm/xyzbJY5crlRYz9ZD6qQxPiP35AbLW0ZtJQiEmhf9VTh+T7MwC/KfFiaSkUj+tETqGxf8pVbsHO/EaZVnSijyylQ9tgo7zDZ6uZFhULjZIJLsmxs0kJgW0syaoudOzxq+ST0ctCcBiYRdUEfbuXS5hcrDH05UX0h8=,iv:FOF4o2itqAqLj+LyBOjdQvxdmUV6LubAjGzYc2LUxpI=,tag:ZJ43ZtP91GJljnaOis23EA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
