# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-password
stringData:
    APP_KEY: ENC[AES256_GCM,data:sGTDl+bFnLQ+8+Hzdp3pyHsdsPK9mgV5C5iU59E4iyg=,iv:P3GN6LjO2VSLvFNQzxkzAPpo+QzYinR3Tl3lRz2YEAY=,tag:l+/hsl2BjqQNlXEBSChffg==,type:str]
    APP_PASSWORD: ENC[AES256_GCM,data:GkIOwwcEMSTJ,iv:s0q7z4dQXaWyQ93Eeukd07/l1Yl7IsRcV+CQiZDNWSY=,tag:jgI2myjWPTUj5CHf7W10gg==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:n3mKRLgS2zXII4RbpJ1XFbSavBqSGLWgLrtnrLh8khA=,iv:1jccHkGVkWV5rsNzXrkdhtoMctOQI0MATNkHw29lcP4=,tag:kp8+doq8ZTpnXTQPSlgxvw==,type:str]
    #ENC[AES256_GCM,data:fhgObRGscJMXBqjqF2XwQLMFmDakbfsG,iv:2LSHPSaxO4cLso64LvmqKaYY3FQ+VEnf7vWYK2oqFWU=,tag:jgcpxsB933OfJKNbYNnNcQ==,type:comment]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaTQ1TUZxbVZCOTJYTTJI
            c0oxdUY4ei9PWTJWVEdvL1pCY0hjV0R2ZVN3CkV4V1BZdTQvYmh1bkkxWHVaZzlu
            Uzh5QzRCVlduNnFFQzNsL2xZaDNiU1kKLS0tIGpSWWNFZURyQUNoWkpMSW9EVFdF
            TGRVeVVEYXVyV3JZV0JkRmZ0MDVCVU0KCzYvDPFrWAIU8bKdN7wCl24gVGhT361l
            kyeIfQw48cutc/0ZV5z345s2IcgQCBpPz8EzGVnuHZPqaWavb3TMeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:14:14Z"
    mac: ENC[AES256_GCM,data:+19sW9q4xHlYMRN6/S5IQKouXHkA8SVJDdh7hPw8BSIY8gYuupBLCSJz1rPJ/3wWSR1BGOdKfbbWDG9H11AsO+af3peXyWhFjRkal5fHzkXv6aG7e3XsxBxS7rN27v7088u2t1AwrkE2uRPbVIGcBkpfpXw8H7uWRSuETyz51Ow=,iv:oWCTFu55SpnoqEAmIuIrHA8Tm2dS8vBYoi7RH++y8mg=,tag:kQTkfzrJ3DfOYAe30KinMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
