# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-password
stringData:
    APP_KEY: ENC[AES256_GCM,data:7Ror7RIXpZRwoCnBTkyDrWdjhL49Vsw4SWqPwGOeEzc=,iv:w7U7RrcdtNI0nvVoISTcNLQHW2ttqUhvhVtL9ca7qx4=,tag:OqdhtGzPrcb4m3u6NE/hQQ==,type:str]
    APP_PASSWORD: ENC[AES256_GCM,data:nS/pA3hjngAk,iv:Vjm8ac2BIs/ZoiaGBwSaAgPbfh8PNBc066kqEuWP1ts=,tag:/p1rthCK08V/J/Jn5L774g==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:4WSWMaj5sw/xq8ozJ2sPetuOxOQeVw+FQ+7qj5dwGFQ=,iv:O8t3NZmR9wlCcKwOKswI0VovBoM25k5g3n5NQzPtsMw=,tag:avf8P4VCXOrKljczUaNRPA==,type:str]
    #ENC[AES256_GCM,data:pTP1pPrSZfV12qBBzWpV0bfwzvPb2aI1,iv:E51t4F2AmbrT+yBndOON6gVyU6/99OIKEo3vFTRxMzM=,tag:zZEvnbvbxEnfgqHcDcGbqg==,type:comment]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaExydkN1Z3hGSm4xVnJS
            THJKTzFjRDVVT3NYY3BPYSt0L3I1TXVqOUJrCklaRmNsajE3QndGQ2tVUU1laURS
            b3FJa3p5eENyc1hnYXMxdjh4YnJ6TE0KLS0tIHBWeUFHYnZrc0QzZWE2UE5kNUx3
            Vm1JR0JaTytJWU1FbGJBcVVjWTVkOXcK1PVQyJ797Oa6qgwbz3MCGpSa56UYKdNB
            Z92J8IsiMq23MTEZoAK9OTHyCN8emeMPWef+cYroQpkfLagh+pwvew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:19:55Z"
    mac: ENC[AES256_GCM,data:2AeK+w3waGB46sXyNTtkQJvvoN0LajuLNyiFqu6uYzNGrM0w9HBBzeqXjMoM7dU6oq16Nqka3/U+PL7KcAGAipkUBU8+/P7p0x+vWs94LVBzOllNwJjgCtiR40WOwTkGp0BIUEY+RcC6bYMGJlstGuOCQp+6v/JfVm4y19kDcrk=,iv:OwtGrgu4i1QszTUvtiHVlaXRrYX99FNLXJ5cEcmpHzk=,tag:to3XZChUzHsClOm7rCBfHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
