# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-password
stringData:
    APP_KEY: ENC[AES256_GCM,data:E0D39AhaRuym43IqifXPYMToEu3KXAjkSvq11sMMsyM=,iv:i+VcRR9GyueoBKLKtJJXAauHyQ82BCQkh5k+hm3Vj0Q=,tag:aZ6P2uhh8+dGyDVTYLjLIw==,type:str]
    APP_PASSWORD: ENC[AES256_GCM,data:9Xvq8MmQPUX+,iv:0Uh7C27NhtNTPQZXbC8/INDpbv2/UW8yWBRLnQSWzls=,tag:jK5iEHpGYWnspP3S2So0bg==,type:str]
    STATIC_CRON_TOKEN: ENC[AES256_GCM,data:jqPLOne1KVWK1x4CEG+3c3oz90y3b+i+OHEP6mlpp58=,iv:2MyEiTJPnbiwnEaEJZ3TrRJg8KjaqkIlCSIBs23NCiA=,tag:0Vr/JJcAMbZaN++KRvU+YQ==,type:str]
    #ENC[AES256_GCM,data:TGfJyP4IfmlhbJ1IRhmjD77o3/Aq9IPa,iv:cEcPe/+qBsudgjeeZkhDmyJl8uSZVr9calSw6628/2E=,tag:MfE1OY4PDCzTmk7bOfVc6g==,type:comment]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV3hCQzdEc0NUOTZCQ0Y2
            ZC9GYmNDZE1HVUVUbW9YNmVJcFloVTlYSG1ZCnlFMzVYRkxlM09IUmpTcnhKblFT
            MXBIclF1blp5eHJkVHJjMmZHcDIwSDAKLS0tIExRT2JQOHNDanNYU1hJc1dYM1JC
            a2JEc242ZFlDSi9ENUs0S1BJd0dtZWsKxY+I0if3300LVueNkqpjiNq5SwiTDcI3
            hyFws61v54Dpol2yXiJ7WZ4tZaih/vm4O8qyfvl2YmiEa4qIlIOkEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:21:17Z"
    mac: ENC[AES256_GCM,data:6KQA6fToijzkHC55KaMKXX3gt8vqWtzzle9c9syeUxvXy9mND0Dk8YgSW9DyqThuqZedAHHhgoVDxP+0Cq7X+dr/m0OZSCU9J3nK+XARF5lgQDxqGS+J+kXpSMNyTAPOWu5XcdgZjFFp5Jp6W+nqFunWg9Y2ZZVljZqX6VIJhAU=,iv:+zwCiJIvemhVkxZJDa/MmjMWETrK1ca3QfoeB7EKv6E=,tag:1ekdP1JHhD4Nv67FNe5EDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
