# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-token
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:g+6MoCLRX6TANvtwE10tcRNilKGmmz0YWiSBlDMs6QTLh0OrTEsZVF5UIw47cuBeqokV7rVasxdvuuShZjqWBZCNpPUoHu4ptaN+IoOtOyAw00IEgGt2L1p1BOKtgHTP7h0MuGOTqsv0B1dP5PhtcmQPtp4dYcfR6PJq8xGT1X2rTGiIAMevaMvVCDj/EFLDHTMtXs05P80ne44HhKUyE76ywcLr2le9FUs1IN3Q8CjZvqMiTE1zVXiJfjsgSTePezL2iGV+PtdktAlJ7GfFOzoPuxMzLWBGQZGSQSUPpSkxmYmMw1Y1Lu3bSGRBtYNHWekkutrpAjilTnRQ1j+1AIiWVWUK4quoxc2CWmMCrH7/LFLTEf6WE+gV4jq0e+nWUSY4soYPnrD9prCPnLQ4isEJQe1XlF8op9pg4J3l322/vSOcHa5y8ugWHmrcq3tEIs83zMV7vJCwI9Iq5j7CPtHHa7TNwjHsYLMAfwdw5hAfd94K0PgwMfhSf7DivC3Hj0gZPlywEezVxtDItG/SY94UoyTFUHtSnTagITTZu2PcPujNz/eRVGUC8z/lzYSoE02fD1xsvETFKva5aX5ShX1PHvwFadEXMJ3GJwwWD76UxBjFN2rVjlea7pGtjVWty1xAaUsANiUH6bY3P52KIZxhmwXqx5EU0bMZtLLGSTMj/FtoXG7qi0jKo04CUfqf5a40xRYHvZAeFG1ToIEmnC0Dn8pvieXdfZP2a2d1srIiSSnCsGt4tfYB+AjRo28t50FhmymjWaqRgp3tUwunIvqN6sE0F4YgWlpWsiCtnoLZ4OM0rF8w5g8S9++/19Ubmh8g02dFlzbQyViIhuh6K3Ior4KkFpPA589GwHUoNzCAW1Wf4h9nMKbfEq/aR+fFyEplUMG/gDbtItCUoZUzjt8g5epcCZlBxsyinF8BSmnd3j5cT89FN/VXA1oiDAHPx0CF7K8zBnd6WshcXbpP26d4fLw3PxZlZMXry8+wGdgiEIp7DV4wcRot3rUJ+TsyoNPY06cNSr3CvIeMiYVQzoSRZ6BxKYAErbtA/mC9UbNvt2RIAf9mYdFAMNWpANZzn8MmiK5kAjIw/Ur4hJLTrBaufTOBTWRvyWlTO1HR9hkhnHY4ILyIHWWOiNdR1eu6Lfbi1DyrmrWSX4TmgqFrFGRsJ8Jvq62SjstMNEisF9FyZqTT6/SnEUay+OKtXmyPVZo34TPg5AYtsT0OBtzb5AIi4uCGnvue8Vck9yBWB7pdxnUZnkAaQ00GOw9P5dZi3iE4oyGf/iCorO9y+NPW6EbNtJA=,iv:ZczlqR9qfJgs6fk/ZRer0p54Bf9BsQKT6K7xEhBuXpY=,tag:RUK4zCcoWDJSjARvZ7CtPA==,type:str]
    NORDIGEN_ID: ""
    NORDIGEN_KEY: ""
    NORDIGEN_SANDBOX: ENC[AES256_GCM,data:rDlEJRs=,iv:nL4nnk6QA5bxE1EoIrbuvnDkTDStIuHX9nDuPu5Pnug=,tag:7o7rIwzX2XQadmZdG51bNA==,type:str]
    RESPOND_TO_GOCARDLESS_LIMIT: ENC[AES256_GCM,data:QXZf8A==,iv:U6S8VcizcoJp/eg2Wkpu3zN2tCh/XtqSxApJKAfFdqU=,tag:rIWWZM+Y8wSm/EnOWtSNKw==,type:str]
    GOCARDLESS_GET_ACCOUNT_DETAILS: ENC[AES256_GCM,data:nih/4qA=,iv:iae/T96UF/DIr8P1rCe0bpri0BkmqD7u3uWD0KLKatI=,tag:Sc55uX0ZtnD5PuvcvlopTA==,type:str]
    GOCARDLESS_GET_BALANCE_DETAILS: ENC[AES256_GCM,data:6O5/5gs=,iv:MZqqKcCjfYfnrXewOL+Pk4wgm5qK7vwXn9dHcFZ072Q=,tag:PbYROAPIQ8LIWgKpV/NIAg==,type:str]
    SPECTRE_APP_ID: ""
    SPECTRE_SECRET: ""
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:QneNW6xl5ZmJRuEUDtRf/Q==,iv:EKQ0hVNctLs15AZvzMO9Yzz5H7DhplAsEgjeIEdMcJE=,tag:PpTaMJDBFElzOne3nqT3DA==,type:str]
    IMPORT_DIR_ALLOWLIST: ENC[AES256_GCM,data:IPIPexW7iNtJAmVV5/GtP2h8U3M=,iv:ZwulR6HGTlkhYFRFn8oF7B3YsWMszPOezDvk7l0F0us=,tag:wP1aAPc8PVznN1wJmcPHXA==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVGkxUUp3MXd1cStXTmIv
            bVpBdHJzclQySWcrS2ZXVmFYbEVaQlA1OFFRClhvMkpqSUZOTjlqSy9hZzV3c1JY
            ejJvUUkrTnpBME9GRzhLZHA0NnBMVDAKLS0tIGxvRENBeWtTaVZKVkV0RU5UaTJr
            clI1QXNpOUoyNWhuSkl0RzlWeVdXdEkKhjVJg7VA0uBv9kWEtASGr1D7z55rh6j+
            hV9ByL/DTWUaSIsXzFOFXeObq6seLbUoqeqer+2ZD4my0AesVeX7Jw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T22:08:59Z"
    mac: ENC[AES256_GCM,data:iA0vinPkk8ITO7Fsw5tj0aEceZYgGH6/DYLTyrlgs7bchqyii011UM2+LE0rB3ZkWojY9JDNa/ndLOugw09XNOenBr3IUfK8SKKGNJ+UZCddmTDIzfK3ltEag5Zfj5piVQyPRrODi8jBXcLFRHK8ELCpfkTf87kZ5BLxZ5kPWoU=,iv:soHaNG6xnKs8+13I2awUNhg0I7XJ3bwcJRkRAfhLUH4=,tag:/myMs+uj1w3CRZYOYKGT+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
