# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-token
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:jxRdmSMEEeSDhC4CvpOSfbeCeW72giJTav2Nw7Gto6mdk4Ys4JyNA7AM9zEEDQGxr1GggPuroFyaJaDUTeHtOCuWhaanyN/jqCmUKGgP4Nx6G6uzp/2F4hPYNYd/F1N8xPv5uOKbe3foXWjfGtzriiUZnRHGCBbEsAgwbo0IrOxn+LSg39cpc8FOFnzxSkqTv76gtXaHAh6fn8vhh5iA+dwKcK3tCtdLOvmFf7+XDVX0X+LpITZCtD+HM0D65V4GmPy8hiLL9+Pss76l7AK07nLuzM8f2bWzJsr0s5DGJrTseXnRxDHjPmO3EfQzJ9gnCd5FGohi8U2+2xZcOUmeuPBOFLfN0k1nzBQg+pE8Pk0mNlg23uG64sGCCHij8NWAKdhmPi5D0Usd/z/bMhzqpmUaR9QeGrGtUy+hiXIYfMNrooB5kNms2kVpx1END7lp3QNlI7M8WOQiwU5eZQC1p/ugoFuX9LFhRdRqrAmdaAsNRWQzfpfv0biLiOq4CIDyl4D7q/sga6p28+R5ABYOzxTQiXKhUFieivUMsGohMxnJ/1YgtXGIz3CkkWFLyzgQOCynLlPlr6gZIvAfHcxQucs9VqGR1AppMVdWGBH/pZHIS0bSdggIKqfUYgRVrhjqLLtl+lVcBx3SeD2Tx4CM6GL/cr+tSVdY/l8T2//RUDHgqEX8J5NYQpbAYnLln+kk3TjRGEUYmWCzY0hFikwMXJ6EdFC9dIxLINpqHHCK7PUE7ZH2Ns8XioGQhwutrBUebrThLnicI+Uv2C0YJmkQdI3AJTf1kpIQYHRA1iqQ7pzU4tqvtmkGs+CgvnTXOvcAh2LGGRsGgEwfKUifx7+FZ2LSCOSfIDTNwZnWn4Ds+MA+banwIPsu/SW78gL7gM6X8MXsaw0CzEs1RCGWXh1VFZdQpSdO6ZaQ9WbzqTl9F3zbdaRak/A2/aLwbrPOOioeMI5Im44LdPivvkSoD8CVlQOllX+GMBOJ1pBnjVBua7f7lOUFP6fc7GngS+hM5JRA+l9T2sfVlWCex60JkOMMsNtq1BlNhSeB39sJzxE6SSac+uGwbQFdm1HDY553Cq6LfmghPLAhbjECLmUNoJaFVZto09PB0b8Gv+tQvwURmlPUfNEv/IDHj/Zi8d13M55QXgzgWRgCYq33h0HfIP15GSh7+/xnpBRygjWy6FmjIvxDhGjQSkzk5y3Js7BQ4/1DmPrejlaUZJhxo5YdiTPC2nlEdS7fIHo7W8AMsJo+OkF9TfjcbukMpKXq6TLgL+QHmBoBWcpa8QAe//aFUbkfqmQ070s=,iv:9cvskn86ZYkYWqDkKSOXQ3A8w/mgiyHdUOrv8ucFljI=,tag:nZSlNGD+llPLjpcoYOQTFQ==,type:str]
    NORDIGEN_ID: ""
    NORDIGEN_KEY: ""
    NORDIGEN_SANDBOX: ENC[AES256_GCM,data:0hoA780=,iv:Ut+vTQ/9Yu7QN3viAkvEec9qESjW7s0dut33bg3T/p0=,tag:5f+SYGsEmwh0B/6BEXJ4cA==,type:str]
    RESPOND_TO_GOCARDLESS_LIMIT: ENC[AES256_GCM,data:TF3z/g==,iv:GVAFYIwAv/+uXPcsrQOa60MtnFAZPKk/I/C9guxunZ0=,tag:iC9liPwIWrygR3HToZSVlg==,type:str]
    GOCARDLESS_GET_ACCOUNT_DETAILS: ENC[AES256_GCM,data:wwv0JrU=,iv:RLPSfvuaiKmhF/rXgr6nkAMyYYvgV0/RSoTuq4rhrFc=,tag:/bi+LyKQFoX0SKdzqu6/Yg==,type:str]
    GOCARDLESS_GET_BALANCE_DETAILS: ENC[AES256_GCM,data:bT5Nn7M=,iv:wt+0Jvpg+RCXNYY45mmnUdWCBwHzt2Wbnus15uJ/BHY=,tag:Uxq8IwBVikbSwINN6+CA2Q==,type:str]
    SPECTRE_APP_ID: ""
    SPECTRE_SECRET: ""
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:28OuNbfk8AiqQfXNAnB/gQ==,iv:a41DX0he3qsOBJSXlAgj4/5EfwZtyY+wLWc26Mih0KE=,tag:IfcntuegJOA+TJEetYgq0g==,type:str]
    IMPORT_DIR_ALLOWLIST: ENC[AES256_GCM,data:9Tcnvcx24V7CZnC4DtBdU51u8HU=,iv:vtOitHOiFhxL8OoexSZhMgIzdeCEZjBIshOaNwJRwBA=,tag:3bNoLpbn7GbGAuDU/ttmkw==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoS0U1VUJoTkg3amI0UkZW
            cEhGdi94ZGFEMjFGUVVZZU1PV0JJaEF2cW5NCkNVT3pGaXlpQ3R2TTJxWWxEUmVZ
            alhQRnNVWjZic1NUclRBcklUWkt0TWsKLS0tIHFqN1dwMXlGVlVwbStJbXJOU2lB
            aVNDdmZkQm9rUjlRR0hiSFJVY1loMEUKAXvTOgSOh3p/VzfzCI5PpMiVKh8OGQRs
            MEZia5deqklTzHYwixbFeYb5UzxoM4He0UplYVI43UmluX9/9ZZj9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:14:14Z"
    mac: ENC[AES256_GCM,data:KJqpXSns2oG9XSjQWFmk6gJ2576/MTHAkI6O/X4qU6WtW3pR8q42bFu3CGuLIQxhLlnCFBXbo70DHhYoXAUFmL1ZC5ou/tN70mHWfsMWPIWjxQjrJVsupeBqXCSRIWErxbh8jdV1+uEiumbVgcmvpwTNeEKk7/H+K8VkC0LrGco=,iv:hQlzRKpBvJUMPwtVaqW4poV6s/Fj86wDOy5GSq2YcQM=,tag:1BO6lkVT38kAC1TOaC9gHQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
