# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: firefly-app-token
stringData:
    FIREFLY_III_ACCESS_TOKEN: ENC[AES256_GCM,data:hbmXt6GSQxIHNuxYYmiC8VN9223zFa7uGkNsCy9jHiqTWpPJcX79mpSHX8JMX7yB/jyU49XELz3g7LFS99ECW9CVh2GG8UyCWkf94NEWLBGmyr6G4jL+XqQ6i4mYtunXfEd82Mme2RyA/qus3WDX2VQ2RiulEJStA7QO/4TMsvkwuZE6n47RW91J/wd1eKFMevBExgFXbonGzSOf5fMq0FM6joBGZXl2cH2Cyk2fhrZUosYwkzjL8PIyfK3rgqexRb1FZpB4DuEHsaga/NGsR5vRITRRiNQAIkFCG24daHmPN4m0Vria4ikHyYBEWx8HZIyKPJy+2K/JB5dZpcduOw+dZPqyr4eLBnSWxMXSp3nTZzAjrrv4vDfUZSw5DuNXFlnnB1nFHc9T70rrd529NRdnCgJJlfXdHVPbgqdWBiEKMWadG/776SIIgJA4x+DjixZNtVev8fpB1ucXM9Pz/qgvJcI7Fv2GE2DGCut4ujvgiK9Qt8R7d7Jt4ZOmks0HYzua4DrFvzDNazmV7mYK8w8tk3+Y0d4e3CSDgYk9nyHjMVimRxhYZrxZUeY+AQ363ZyEfDc9/PQifAp398z0vuSQ/vsvXd4CVjgj68UOwfcz32EWpk2nsbdC65XiCbhYKO/HgsoV655ZVGP5TbMz1+ae6q0c32p/AeqjF4zVQ4W/DZkpKKS45ZVRB3sRMxGd3lzCnr1PmowrL1LGtg0Rcf+nVr1DSyUKwTVV5dR2hB++Zmm4j9YyrMYkchLA8wwpKxz1vlcWqjVArFtj8arbG7eH6bMmJXmWePxfognhrbX/Fvt9WnMwgAuidPOAb2aAowUrgnR1YAR/WyTqO+4wONAleknGpGGkj7Dz8M6OnaLXn4J3H3DdN5OsNN/MvRjMKdDm0uOD3lwUE9tFrZcVif2WaSePq19sLBqFZu9JGxa6SWb+Mj4cMr6cK+se7op7snw0RBFsoRDm7i3h97enO7VYsPXdzKs2lG5G7gn6dWeJ4PYAP7uwHk457eNlFC8HCDeCCXpA6P2W7BVHqNl8H1ngE1tnLcPDRhjawzVBCeKM1F1iD3k1yop9ASmf1TAHyf4X5lkE4OHWKN+Jb7gF3wh+Gs1fbdnXGnHPXgPXiC4dxrFmDOx+Ay56jMNQPYH/BzSh6wAok4i4xinSN5cifBdRUyi8buOloUeFXE9TIA2LMFYO9ttsJydjcC++/9LPnQ0QSZ/LulIphsAex2cqBAacO1bDJnvPsxNQLf0AyWU2rNI7fp6D+CUO3FhOsUZqWy5A7S2I89j0jFvnjq8+APuorlo=,iv:Lu/F0cUpInPCMcZFM3F1ziS1ldJqMsy+20rPyp3Oaq4=,tag:bC27fRXZAGUTEFWSHYlxfQ==,type:str]
    NORDIGEN_ID: ""
    NORDIGEN_KEY: ""
    NORDIGEN_SANDBOX: ENC[AES256_GCM,data:xQI9/OU=,iv:jkaSB/HG+97U40reQhanxLD7ufQK63lCjcpLVPBxluI=,tag:4jB0qAD294rmX3FJeLCEaA==,type:str]
    RESPOND_TO_GOCARDLESS_LIMIT: ENC[AES256_GCM,data:x40ruQ==,iv:lUempR/irLU/2p15AYHVOQkUUn0gLoaVLGcsUuU2x2Y=,tag:t2xv8mRfzOwxK194sw0qYQ==,type:str]
    GOCARDLESS_GET_ACCOUNT_DETAILS: ENC[AES256_GCM,data:9MWOKx0=,iv:eRScNOBDOZGpoNnkuXDv8EdQYd6y9qCAZ3Y245L9XS0=,tag:/TMetuVQgkhuPFPkNyf6kA==,type:str]
    GOCARDLESS_GET_BALANCE_DETAILS: ENC[AES256_GCM,data:QcANgLg=,iv:68qKxbgTIrjJnhw4CSEAxiPz6ooOjjj6i9oq9f/YhW4=,tag:mOcCrUOfjRA3gsfBM+5G5A==,type:str]
    SPECTRE_APP_ID: ""
    SPECTRE_SECRET: ""
    AUTO_IMPORT_SECRET: ENC[AES256_GCM,data:CGYuly8eZWFhipUZiluivQ==,iv:DQQsCCKZtudW0Dy5+hV+hlWtBsf30rJcPsOE2votCVc=,tag:Mweio2V5Hx4nrrzTYuW09g==,type:str]
    IMPORT_DIR_ALLOWLIST: ENC[AES256_GCM,data:5gTLQBTvbwv2Iewyde7xS8b2X4s=,iv:AJefKVsLs8/tPtk6ERhwCGDm4QLpb5ictoCqwMwLt4s=,tag:JCbs6EcTdkTfyWomxlistA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZUhJYlBXKzVpOHZkNEdu
            T2JNR1oyTzZaYjRLQnl5V3VBQVlxU1JFb0I4ClB5MXM0M1JVeWF2d3NtNm9uelBo
            czBIelZMMDBIcy9EMzd5dHoxQmdOc1UKLS0tIExiNUZnL1EwVStYL0FVdFBWZGpn
            UEM0aGlsNm1CT3RSd0xFRVJkU3lET3MKDJgz04KUAK2hPR1Z2QYE6rZylknNxAKd
            OMo7GH5a5xvDQYsv3v30/gzfwpoiKS3aEFec4/SL70VE7KTInVJoNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T21:55:23Z"
    mac: ENC[AES256_GCM,data:NjdRr3na1pyxdnZENvlhN97UsgH3SCmhR9OvAI5MvWTdpCo+54XUPKVR818a5FgKIf+E4m3Jvruay6fbwPxLH3EVVWLaTbt/P1aDqHZx4KKF5hixEVo4/UivVxyd+4p0JfFvapcwIsqzEqSf4w8WVvi1Fh1yXJggGf4luv1GkIs=,iv:s7gdolv42dbaxtOwFOy0gVsWJdxVCuZf9mSJwuByTSQ=,tag:WqdvOU1J5qdJsAbZKC724Q==,type:str]
    version: 3.13.1
