apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:pBcIrDvLv6fLLD4=,iv:mLnrQvi6JJGmSx9Q+fb+OfubCPFPMoPt4l+QEz5thXg=,tag:tOYhtVIqqimb1kXgE8a6gg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:teTuGowsCYqlWwCwfltwCs4=,iv:QN9O6efwI906lEYZv8qRm0ieKrD/9vKTEZ5d5f6FPYQ=,tag:uAzjOdO7NR2RG9qy64Crfw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5WXV8QHeoyQhS8RGUGTUQmKUZtB1TbXA027zAdmKSXxgc/lq,iv:xNK8mm1VA/CCMQJhHpEZKN+1d/P4JwUcaHzlKrTiysg=,tag:nZhqg9nTjv8yAv1qXiQd+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVm05RytZV2RPeG9vcTJB
            WjgzTFluVE9PbXpIUCt6RUpVQ1kvK2U3MVMwClp5OHMwY0g4RUx2bzM2S3U0MHhX
            cDFzNTc3enV4dXJJaWtDd1EvSURZc0UKLS0tIDBhR1NzZFlvN2xrNGhxVTgxT0R5
            cWc5SFBta1BlNjlYN0JMQmFFQkNNdFUKYXT3qrgCNX1Ic9QztDYk2iHblzeNSQFZ
            jBiZkdb6HiUrAhBiwQ/OhmWta3wz4HlFttDwqbunOkdLof9XgHlkIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T20:56:49Z"
    mac: ENC[AES256_GCM,data:NUkPEfltUrOff8fWAn0Ni0eI43B59aEAhjmjwTCc0d6WQnPpAFo7VoGLzLtXY49AVRvuAWZeY57ExKI+oI06xcwW0S0loYSIgsySK3gpbjXQo+evixrJLN8aXuGQBibAGWLIfZKcNDuLMfLWmsVoUApTqFN2BFI/aKyL9av/cZI=,iv:0LxH8BeOrOVpn1VZifg+RWXWlJfA4pMDcd1eK3X1i8M=,tag:VIwe8CJCyH6jwsECUoPAKQ==,type:str]
    version: 3.13.1
