apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:RaXefpNX0CSszb4=,iv:POIgdeGOM1oB7ycoyUfHuyMJlwOD13PcX+oGO5BztPA=,tag:wHsr19ROGoyWMIH4d/wWjw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:7W816FhXvi/aYuSQhmW9EQs=,iv:ulP8B35oMom5bk+zfjRyZMXOlXSVePvsWXuNa2jg50Q=,tag:jch6JwZqz27j52m24NU/Xg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:AM24+WVwO19NZHUgQsRrou/4RKU2K9GZG4Had61TQZ/Iterz,iv:7b6srQ4WeHa+7dbRzrJy8ij6qKNbSAAB4JIH42URuxY=,tag:4/pZjTU5Eb5R5MGAnPd/lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR21Jd2JDVjZzaTl1eitK
            aHFncisybVdWN1B2U3RSRENRYTQ5QktxeXk0CjkxMHQ1TmJYTFh5UStERlpmNis1
            SklWdjkraXNneGxLb3ZZNGVCQjh0LzAKLS0tIEhSQ1M1TmRveWRMZitxUEpweDd3
            WmhmRmphdmlpeW1EZitoTUxqMTdRdG8KJhuu2jBRjkZROsHJgTHayP1aRohG3yZh
            jteY12fsWg3+CLKLPCMsNMpkCqWGkVh8J1qKT50/kN5fXmD04ilNhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:37:45Z"
    mac: ENC[AES256_GCM,data:HcL/WwBaL6R87zNcJB+QCX2p1OxKnPSKkYD2c8zlJjCB8owykppdabi0LDNdFi+8CUcMGL5NMFZWr7xUyaXvz2oUdhVrHYMy3zccsbfTBkE8DJyxxVMZSW3av2JUzAir06dON7h52+IB0NdhkQdY98OyVSAvcpfzgXJKQCloMJE=,iv:phCWPO/1n45kgIF1HYPG3iugchiLBUoRV9C65LvZOfg=,tag:0LtixbZ5tG0sUfFZzBcVHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
