apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mvfj/u1lxfQT5BM=,iv:qTv7Sx/eTH864FXarA3jN+pR49Ttc7BWEt6ZkdF7KVU=,tag:Rx3tLjZJkiZ46A9svoTpsA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:F7/dCUuRoNzg7a2BVm47nYM=,iv:Hces/PiQG5s65TZF/khxKhaLX275sRXjrzlW7dIc6PE=,tag:Pkaw0kiZBreE9F25WR9HmQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:g9KcuZEGgcAV+M94G88R393uUBN3c2j9xc9vfNnHpUss6idY,iv:kyiPBDCXMQAyAqlKTpKBL//33pZgnTUbrvIxBdknY8w=,tag:psRrJ/rgps5XlkAGuIKO5Q==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRmdoN3JnQlZwT1U3Sisw
            RnlITlhzNVM5QThzS0d6SUN1TGk1d2J5cWdzCjNGNnFNaDBMK2F2WVpEc1E2LzhZ
            YTlVaGxMZXg1MEF2NDl3NGs5ajFjNHcKLS0tIFRScGFTUTFoMjdyYTd3L3JuNDB5
            ZVZuOWNyUUZYMkR1d3lPWm1kd29CRjQK9/Ct2HV6/yR6/N5qbGjLpEthG3NFDknP
            V3ifhXFdmbtX8y8OiSrau+QbkuUK7iXL7Ewn1sa0hsHElfRCJE01YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:19:54Z"
    mac: ENC[AES256_GCM,data:dHb9X5mNBqU0tiv5qYpC8TJqQpt4QHujtEtrcy9iTBchJoixqYF575vcXc5eA3vdqAQFR+OujhYUrsWDpun5eL/6iB6myXcMVUvaJ+xV2SADRqxkBkG7v2f14nuQfevm5mIaIWrZAefLQyYIYxqWlAhF5uys6JpwlcjstYE/3L4=,iv:DlpS/5Wp5f4yns0pnUqhA9H2LjdXBA+uFRKy/PaD2/E=,tag:tzSVXYrzLN7tt/f9iypkTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
