apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:GrqZgppml4T0qkhv6QRUOVns1bDBsEuTleIdTIXfSKg=,iv:hBJTEhBa3E7be5/sOj4RwmmV1EFHO/HhEJd6uJC/0wM=,tag:GsaK+BEJc4Kx8PIUealGyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U3c4ZGJLRTZNSTJhY21M
            ZTArTTZWeE1JclNJYmNZTWVkZExuMmRxZUY0CnRIZVlQb3JWcUN2aE4vem1ucXhn
            SkJaY29DcTFjNDN0YmdDblZDclVEL28KLS0tIG5aeE1VenFEaGhjTDNRNHdsVzJx
            NE1NWGJBaVNTR2pSWllaUlBDK09nSncK6LJBvvmIeWxPI4UqZE5uKa9KJKONrwfb
            M77CbRTYphq0Gt4pPxdpgBCrP2Os2oOeXELKXzVlWn1tX/GOqjddeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:37:45Z"
    mac: ENC[AES256_GCM,data:4dkPRC6vv3Dt8cFLEybIrrHAAc7JQ9imteGUysnWW4yyuOczGHJC88o6a1ZBJ60ltUCI1wTURSZcG2Az+1t6POtf3P4sSBcVP0A7bBIP2ozlixUWV+yLmd1VIANqYFrl9eznIncMOhHffRlvUeS/V1vPBV4RJWckzdn5dm6wnx4=,iv:oFPZ4xsxwRKY+WzbYMIKiC0Gmf24fZF3/LBXpRnwneQ=,tag:cwTAz+7tNeG8HoQLpNbvXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
