apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:TEqDcQH0WD0RUCGsJ4I6/m8g9Z5gnddTaE77Nwpsfvc=,iv:Cxlkb6rQ17ZgKHKA8AVCwFUKOxT+jZ2C5NdnzEc7/eI=,tag:P8kf8DPpaucwAjzkdc/5xg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1azRzZUV1YWUrcnN3TmFy
            cUVxdmJmaHhHczkrWkl5WERQcHJ4aGQwb0hRCkh0Qm0xU1FJNnUzak02Mm9GamlG
            UXpkN3U3OTlhdDVla1JzZnhrdFVzSXcKLS0tIExueXpiZDBSWmNlU0tpL08vTjUx
            S1pudE9IYnJITUNSSXJ0TzhndThWTjAKv/V6raDgTHQqgQvhXVULBE5pKN4NYLoL
            xWamT9aCBf7OizyJBeThg2NlQZbYdnyMcDrUhj4wYHsvY4Mphc6h5Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T21:55:23Z"
    mac: ENC[AES256_GCM,data:dzj4KKy2BpM51x6OhDweH5qSVsb6pYjQGzXyFFXACYAuTGlxVmsD87URtQvx1SNz7MxugpUaJYlVoqm2U9XlxZVt1an2HBSwW7MZM3w9LaRsJJ5m4MS9f/V7UJzDM602HsZbL+qClmiWKHluPXWDdM3EHJz3wsX4nBdnDWLf4ZY=,iv:OH5OIKJImhSclpWaaYqS6e31TOHFxOOfiZcBdgv5cyg=,tag:0MTIxmT4bzbDiOJWFOh86w==,type:str]
    version: 3.13.1
