apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:FX6uY89HrLXqIvS6pI9Q1xclUWD2RUOxs1cjjxT0MYM=,iv:TJpuarSYHmSDd6LJ/VZoIDDrZDBaOyIBlDIgquq/uwQ=,tag:ViAY0KfOxH0jsfSLCXysgg==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUlNBaHdQR2FCbDMxZ3VZ
            UXFNZ21GbDF1ak9ZZmkwTS9EUVBmUHlCQWpJCnhPU2dCL2NVSlV2WjVOeVp1TnBt
            aDZtZXJBQWNZeVRnQWMxb2F3YW9vcHMKLS0tIGdONkdTUDZjdndNUTByMmJ5ZlNW
            MHR1MCtuQnltK0tHbi9GV1duRXo1TzgKjuKSbcy5g5hb1lvu78+8HY0w5UQcNlg3
            n6VU0I9szFZ1I/tPSgGIjJfsQT32m6LDg60Chh/cWQ82JiUcXPMTkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:11:35Z"
    mac: ENC[AES256_GCM,data:QkIgeyosRvuQx9o0rIX3nIUQ7ccnbLCv58n/lXpDY9jTRf9afZSAZxvpMSetJLSv6vB5qZPm1+dnWX7wnbJUhflIbLmVcSto8ra6SjWaSyGUgIO9kqoBRV0Dt2JNevKKObme/31kX+dm4zPAp9RZYi3t1GeMkQbY1hd64gFbxxA=,iv:TJzjnMgAk1ct3YenYGxvSPncSpCAUP14BK7jk7+x/mY=,tag:lGXME0njJauzwP2vAcy3bg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
