# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-app-key
stringData:
    api-token: ENC[AES256_GCM,data:HOmsHJNWhzyE3swqpeW4QOG70UrCWrkTr26sPr9LopnUVwTy,iv:HfzKRbHl4UXncdA4vh6p3JjFH3oGaiRTd093xLCfsus=,tag:MtgJtroUMQelThTUfdZQ8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbmVVYk51aURyNjR6eWto
            U2s1dDFJY2Nqd2Z5TXk3TUlmNGEyOWxmNHpjCkFIbzRINTNVdk5iV1A0L1R3eXpP
            clBpZHBJMzA3eFBCRXRQK29kb05VV0kKLS0tIE1aYmtvRjVDNWREM2pIUUlsMU9l
            YWIyT0RHUVVTSm1vaVcwWEVNQU9MMHMKpLXvh71iJIlx8e1V6lZuzacrQGD5LUkw
            TWgtfYfbNG8uAsM5X8TXio36c4aBPcLCt5LEjeCLPopRykz5vx99xg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T21:55:23Z"
    mac: ENC[AES256_GCM,data:xznVwvXE1r20M7PDAFpcezgQTaaHl31VHN7gp0aFH+Q0B8x7RN5U3zxlDz/4WzOeWO69f+dhJYj4rcd8FjoxPLzhAgj6Tf6rV9nrMddayuCvyfhJRfP1yUm8I3zi2Ku0xR8534/mIoDY4Yv5DSgkEMwhwl72fJNCukia5KwF7v8=,iv:e0JNBQMRBCvxEKFEg8gQuLR/sLALF2qyurlp41FgD+A=,tag:Gw8UxOtC7hd7GK0fWxseUw==,type:str]
    version: 3.13.1
