# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-app-key
stringData:
    api-token: ENC[AES256_GCM,data:3nMkvk+bLsMn5siMstlKVVXzBHXLQHcX9av5PvQiWeWxp5uv,iv:kbiCc+2yNowMs57VVyLDnnNKFl7fiF8QoIuXMShEnH4=,tag:L5KcAMNg47FIgj0OclrFzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M1lZNG9FTE9PdDRqOC9n
            Vy9QT0ZyR09CWVI2RzI2OW5WVVh0OXFzS0RVCnIyVzFHZGNYd25GVXZRcHBnQ1Rw
            dklWUGlTa25saDFaZVd0ZnUxL0lTeW8KLS0tIHBtT1ZxTThpeS9vb0VLdThhamth
            YVh1RERkUjM0ZHhqU1lYbmNhNisydWMKKJ0uvMcHaGgvRCxUB7wNUzStCmV/cV6P
            jXpuipn1LcFxeOl0CmpTP1fnGW+5UtRyl9Ozovp13/d1xeg9R/2nAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T23:37:45Z"
    mac: ENC[AES256_GCM,data:uWxb//0d1EitxYcxwPzpRV3QD4YYhkvrZC+QwLQlXbrep/Xo4s0uMjZ9y9OyvgV5siIc0iNzrtua4W+DVZawQ/YToOasEGBMD7qpmGEO3GkdoSX0fr7N3HUA/dVlNSxaS38E5xyWnEihHmxq/ZMJFkuy0XpwgVMgS5YNnfLAgeU=,iv:nvM9cIgP1GXWKUGCdcWaABZkTazVlUUhEKsEKQ6O7ZY=,tag:zGjc2YDRSrBoDCvSk7kpig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
