# file name should use secret.sops.yaml.j2
# use below example refer to it
# env:
# - name: CF_API_TOKEN
# valueFrom:
# secretKeyRef:
# name: external-dns-secret
# key: api-token
apiVersion: v1
kind: Secret
metadata:
    name: notifiarr-app-key
stringData:
    api-token: ENC[AES256_GCM,data:4OZfpLIMqSy+LKviR2lSyVdec4Njl0fbk6qv3GvSg7GQ6ISH,iv:XEZ9mKsTHd2GHcsaZArjiB7hI9INGgp/eu4tTmZZMZE=,tag:eqrzZXnqpv+uJu0aVpWeTA==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WXJZbHAray9YdUZhMmtV
            bkxvekIxQnRDV3FzOEZUVS90UXB6MlM3SWtNClVkdk5wT21leTN5ODlPbW9ZYVNv
            VTZ5NUVYQzZScStXczBrbUZON1M4TUkKLS0tIGxFb2YyVitCeFM0VDNjL0I3M0NR
            U3BnbWhXc3dYTm1qTlU4OXVZUDlZL2cK549hYm//8WCZ+MB6ZzJ/2pGqqwjvtX8t
            LL7vi28FQ+ehWdEmcLnMRSQg8jSFhG0xZjO/iccut+KMQzdHAaTYuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T13:19:55Z"
    mac: ENC[AES256_GCM,data:5AP6EO4N5QUJg1aKrUXp66+Vy+l2IJa1lWJ2Bns2aYHMrDWldA2ZeNwmPdjiSngIJl2BUlnPw8InybQryClwIFLoqIByiRergLyw0zBRbXzHxq4UIviJYvIzui6qTJxs72iiF320UI/xVgzVVfjTSr2zbvpxbil2Yz+CxF28E1M=,iv:UFSXfn7If2G+6cRqbecbylGUqmxRVXiDelZHcrrD5Fs=,tag:y2ri+UspsBAMcMROPQmelg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
