apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Ntfy+4jWg8MvDWeaxORNeUag+++4/5bMWFHUrWcP7AqsAts86R7KiQ==,iv:u9WIUCgCxbUBOc8tk7i7Niy/P/3nV/ucdUq4gMRWkZo=,tag:4pkNhmXk+Ah6mWrUMcY3/A==,type:str]
    api-email: ENC[AES256_GCM,data:MnCgqMtmRTTX2Wzf1c6rraiXfj39+NM=,iv:tVsrNYLedUkfmIElvQlDmTz25ebChW8dyUC8c3I3jlc=,tag:3PPW3lR7YLfzrluMtoe7CA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyb2hCbGtNWFBoUm5UL01z
            eVNUd2UzYzNDendVaW1VdVdML3VDQTZpV2dnClNRMng5aEY2R3ZWYWNteEc2N05F
            R2d3UDVwTjlJRno1aU8zYVhFL2RkcEEKLS0tIGtzUjdFSnhKT1R4VDJpZ2xPRFdT
            N2VheXZMUnA5dEc5aXlpRkNvWXBPN00KWWeCEFP3y5+Drin8c+t5A7osQQ8Tukgq
            fRJWX6xUlFuIxlHC/zdMM+RXvAgX+P34ZR6/F58cSHDEGpksJKhcFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-12T20:56:49Z"
    mac: ENC[AES256_GCM,data:GpOdCQ/zfc0oG18BKZRdJZiw3w3lMsDFTpZWHDziwJKCOa7+en849jsLoXxr5LIQrwIO988JoNO1uOR1krRoNOmDM5doY4XrGWOhIChTHXqfVSm67t/aBFJ1j9k3eu0lJHGrNVR1HFV1DSguHMXcSMjUoL1GmJrR2NgjdOI+F20=,iv:SiTD9gYt2+UZCJG2jPqTa2hgnPMF9LpxaQb5ie0PrW4=,tag:iSE+sQ7ndA3hTGLkLxqRpQ==,type:str]
    version: 3.13.1
