apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:VjtqcjW8lDc+XwaP73SchuWPGTDp9fpcv2XU9llLKpdkMY8UshlZpg==,iv:byLyu02lsVcAowkvCl+gRusl8EXvbYzqJXgpKvZsINk=,tag:FT6jfc6gngmanN3h644goQ==,type:str]
    api-email: ENC[AES256_GCM,data:U/M7bROen2mAc8XC1l/KKdN6YatdEA4=,iv:2HTGtGbxr/16RQh2GxBSC4IYfdIgnP7s2bF2hCf54Dk=,tag:+a0D2i1IVdL+CyzrT1UeKw==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaVE5L0IzRHFmWmF2bVE0
            ck8vTFBJRHh2ZTJKSFh3MVMyYjhOQ1JYenlrClZGOGlyWEZBOGxta3ZPdkxOemdG
            OEFSNjdOZkVrK2ZzZ1JqUmtsN3kzLzgKLS0tIFM3Q0lsSjZjR0tZdVovWkVaZFlN
            WkRPOTJ4MHhvWTJ5Vnoycm9Femo0Mm8KIj8arpduQBKnYYtwXWy1QjwjjGDE/bOi
            ybtAvzdlxpPgxvVuoKBdSqONsioXXPlXk8LuMTQ3UowU7fs5qFRuBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T15:11:35Z"
    mac: ENC[AES256_GCM,data:vGW0MC8n/fB+2Kd5fs7aggxSMOu/I/BAo2l6DKzRZwFxlvwHcBhLaidI+AgkHoLEyortg8S3spqjbJqyiIBkrDkn/3CRBhkzWF50kCWRyEhR3zkphZvc/T9bqR/8+znnO3Ao0T3Q17VTHuBodpm4WrRiHQ1HPUA5o49IvuGofak=,iv:oHDBlOsinNV6kOwfqGVHSx4FOzKGfOyTs83vdyDAmJI=,tag:AjhHe7OEBn3AnP9hc1s9QQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
