apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:gugpj1nEiz6iSkBBU86kmkbwk14g4oXY9WI6YXlciCISNmRVHttTJw==,iv:T6lI1iEfgzrBCkRRtfarHbuliOKsqUkfwqMTAaGp3gc=,tag:pIdDogD3dVAOiwckeaSX3g==,type:str]
    api-email: ENC[AES256_GCM,data:H3yVX/NIf2SJEwS/GpuvhOkEv1F+evs=,iv:NtvM7nZJgTZWQvmLG9VpL14esafqyyUHKbMIiJzPFQA=,tag:p6/x9p133iZgQGNhvWtJfg==,type:str]
sops:
    age:
        - recipient: age1fwp0va68tdryz0a4rudy6m6l8rta5khqjv8kyufq5yg5ykpgduns6zhrcr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwKzVQYUFxMlUxNW43Y0t4
            a1lNbjkvOFMyNk5sVVpuUU5VT0c2cDArVHo0CnFsVE9zM2tNUDBOVzJ3S0ZzVnNQ
            RnhhWlNLSzRuV0U3WFdUT1lPMWp6Z00KLS0tIDZlSHRQNEtxMU1MaHAwTmRkdHo2
            WTdIc0NtU01qbGJsL09halhSUFVyc1kKa/c7dMLHHZ3shnnWuwA9mkgAZ2Gkw4AP
            seuBousbJ32uFCJ9vYlFwxbaVRoC4GMlP5BTNpuns7oGr/cw/IIBhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T21:21:16Z"
    mac: ENC[AES256_GCM,data:pQfDnd4PlB1RiO9FqAkqBgWAHtJj4k5wyuxWIRX+E0A2k9MtXhtO0tp0S6p3WyMXyqh1mg72lZfMKKvVq8UXyUB5JzP1oCnTBqEQQbNnl9dnmtwCwOBUWj6BnsDNXXrpt5OSeKLckizD0mLU6ht72CM7Qx5BK8cYa8tdUrrlMvo=,iv:TJoev6YsFJAP15wVPgs2Ey8AcI/On8y95hSzvJt31eI=,tag:gkuzd30f54Dp5vEZS076wA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
